HC      = ghc
HC_OPTS = -W -Werror -hidir interface -odir bin # -fwarn-missing-signatures
SRCS    = periodic.hs compile.hs test.hs continuous.hs verify.hs run_tests.hs

.SUFFIXES : .o .hs .hi .lhs .hc .s

.o.hi:
	@:

.lhs.o:
	$(HC) $< $(HC_OPTS)

.hs.o:
	$(HC) $< $(HC_OPTS)

Verifier.so: cpipeline.hs lib.c *.hs */*.hs */*/*.hs haskell.h
	ghc -O --make \
		-no-hs-main -optl '-shared'  \
		-optc-O lib.c CPipeline          \
		-threaded                     \
		-o Verifier.so 

xVerifier.so: safe.hs test.c Haskell.h
	ghc -O --make \
		-no-hs-main -optl '-shared'  \
		-optc-O Browser          \
		-o Verifier.so

GUI/EIFGENs/literate_unitb_browser/W_code/literate_unitb_browser: Verifier.so GUI/*.e GUI/*/*.e
	cd GUI
	ec -freeze -config *.ecf
	cd GUI/EIFGENs/literate_unitb_browser/W_code
	finish_freezing

run: GUI/EIFGENs/literate_unitb_browser/W_code/literate_unitb_browser
	GUI/EIFGENs/literate_unitb_browser/W_code/literate_unitb_browser

periodic: periodic.hs depend
	ghc periodic.hs $(HC_OPTS)

compile: compile.hs depend
	ghc compile.hs $(HC_OPTS)

test: test.hs depend
	ghc test.hs $(HC_OPTS) -threaded

continuous: continuous.hs depend
	ghc continuous.hs $(HC_OPTS) -threaded

verify: verify.hs depend
	ghc verify.hs $(HC_OPTS) -threaded

run_tests: run_tests.hs depend
	ghc run_tests.hs $(HC_OPTS)

z3_test.txt: bin/Z3/Test.o
	./run_tests Z3.Test > z3_test.txt

unitb_test.txt: bin/UnitB/Test.o
	./run_tests UnitB.Test > unitb_test.txt

document_test.txt: bin/Document/Test.o
	./run_tests Document.Test > document_test.txt

tests: document_test.txt unitb_test.txt z3_test.txt

depend:
	ghc -M $(HC_OPTS) $(SRCS)
# DO NOT DELETE: Beginning of Haskell dependencies
bin/Utilities/Graph.o : Utilities/Graph.hs
bin/Utilities/HeterogenousEquality.o : Utilities/HeterogenousEquality.hs
bin/Utilities/Format.o : Utilities/Format.hs
bin/Logic/Classes.o : Logic/Classes.hs
bin/Logic/Expr.o : Logic/Expr.hs
bin/Logic/Expr.o : interface/Utilities/Format.hi
bin/Logic/Expr.o : interface/Logic/Classes.hi
bin/Logic/Genericity.o : Logic/Genericity.hs
bin/Logic/Genericity.o : interface/Utilities/Format.hi
bin/Logic/Genericity.o : interface/Logic/Classes.hi
bin/Logic/Genericity.o : interface/Logic/Expr.hi
bin/Utilities/Trace.o : Utilities/Trace.hs
bin/Utilities/Trace.o : interface/Utilities/Format.hi
bin/Interactive/Observable.o : Interactive/Observable.hs
bin/Interactive/Observable.o : interface/Utilities/Trace.hi
bin/Utilities/Syntactic.o : Utilities/Syntactic.hs
bin/Utilities/Syntactic.o : interface/Utilities/Format.hi
bin/Logic/Const.o : Logic/Const.hs
bin/Logic/Const.o : interface/Utilities/Syntactic.hi
bin/Logic/Const.o : interface/Utilities/Format.hi
bin/Logic/Const.o : interface/Logic/Genericity.hi
bin/Logic/Const.o : interface/Logic/Expr.hi
bin/Logic/ExpressionStore.o : Logic/ExpressionStore.hs
bin/Logic/ExpressionStore.o : interface/Logic/Const.hi
bin/Logic/ExpressionStore.o : interface/Logic/Classes.hi
bin/Logic/ExpressionStore.o : interface/Logic/Expr.hi
bin/Logic/Operator.o : Logic/Operator.hs
bin/Logic/Operator.o : interface/Utilities/Graph.hi
bin/Logic/Operator.o : interface/Utilities/Graph.hi
bin/Logic/Operator.o : interface/Utilities/Format.hi
bin/Logic/Operator.o : interface/Logic/Const.hi
bin/Logic/Operator.o : interface/Logic/Expr.hi
bin/Logic/OldOperator.o : Logic/OldOperator.hs
bin/Logic/OldOperator.o : interface/Logic/Operator.hi
bin/Logic/Sequent.o : Logic/Sequent.hs
bin/Logic/Sequent.o : interface/Utilities/Format.hi
bin/Logic/Sequent.o : interface/Logic/Const.hi
bin/Logic/Sequent.o : interface/Logic/Expr.hi
bin/Logic/Lambda.o : Logic/Lambda.hs
bin/Logic/Lambda.o : interface/Logic/Sequent.hi
bin/Logic/Lambda.o : interface/Logic/Genericity.hi
bin/Logic/Lambda.o : interface/Logic/Expr.hi
bin/Logic/Lambda.o : interface/Logic/Const.hi
bin/Logic/Lambda.o : interface/Logic/Classes.hi
bin/UnitB/Feasibility.o : UnitB/Feasibility.lhs
bin/UnitB/Feasibility.o : interface/Logic/Const.hi
bin/UnitB/Feasibility.o : interface/Logic/Expr.hi
bin/Utilities/Error.o : Utilities/Error.hs
bin/Utilities/Error.o : interface/Utilities/Syntactic.hi
bin/Latex/Scanner.o : Latex/Scanner.hs
bin/Latex/Scanner.o : interface/Utilities/Syntactic.hi
bin/Latex/Parser.o : Latex/Parser.hs
bin/Latex/Parser.o : interface/Utilities/Syntactic.hi
bin/Latex/Parser.o : interface/Utilities/Graph.hi
bin/Latex/Parser.o : interface/Utilities/Format.hi
bin/Latex/Parser.o : interface/Latex/Scanner.hi
bin/Document/TypeList.o : Document/TypeList.hs
bin/Document/TypeList.o : interface/Utilities/Syntactic.hi
bin/Document/TypeList.o : interface/Latex/Parser.hi
bin/Logic/Label.o : Logic/Label.hs
bin/Logic/Label.o : interface/Logic/Classes.hi
bin/Z3/Z3.o : Z3/Z3.hs
bin/Z3/Z3.o : interface/Logic/Sequent.hi
bin/Z3/Z3.o : interface/Logic/Lambda.hi
bin/Z3/Z3.o : interface/Logic/Label.hi
bin/Z3/Z3.o : interface/Logic/Const.hi
bin/Z3/Z3.o : interface/Logic/Classes.hi
bin/Z3/Z3.o : interface/Logic/Expr.hi
bin/Logic/Theory.o : Logic/Theory.hs
bin/Logic/Theory.o : interface/Utilities/HeterogenousEquality.hi
bin/Logic/Theory.o : interface/Utilities/Syntactic.hi
bin/Logic/Theory.o : interface/Logic/Sequent.hi
bin/Logic/Theory.o : interface/Logic/Operator.hi
bin/Logic/Theory.o : interface/Logic/Label.hi
bin/Logic/Theory.o : interface/Logic/Expr.hi
bin/Theories/SetTheory.o : Theories/SetTheory.hs
bin/Theories/SetTheory.o : interface/Utilities/Format.hi
bin/Theories/SetTheory.o : interface/Logic/Theory.hi
bin/Theories/SetTheory.o : interface/Logic/Operator.hi
bin/Theories/SetTheory.o : interface/Logic/Label.hi
bin/Theories/SetTheory.o : interface/Logic/Genericity.hi
bin/Theories/SetTheory.o : interface/Logic/Expr.hi
bin/Theories/SetTheory.o : interface/Logic/Const.hi
bin/Theories/FunctionTheory.o : Theories/FunctionTheory.hs
bin/Theories/FunctionTheory.o : interface/Theories/SetTheory.hi
bin/Theories/FunctionTheory.o : interface/Logic/Theory.hi
bin/Theories/FunctionTheory.o : interface/Logic/Operator.hi
bin/Theories/FunctionTheory.o : interface/Logic/Label.hi
bin/Theories/FunctionTheory.o : interface/Logic/Genericity.hi
bin/Theories/FunctionTheory.o : interface/Logic/Expr.hi
bin/Theories/FunctionTheory.o : interface/Logic/Const.hi
bin/Theories/Arithmetic.o : Theories/Arithmetic.hs
bin/Theories/Arithmetic.o : interface/Theories/FunctionTheory.hi
bin/Theories/Arithmetic.o : interface/Logic/Theory.hi
bin/Theories/Arithmetic.o : interface/Logic/Operator.hi
bin/Theories/Arithmetic.o : interface/Logic/Label.hi
bin/Theories/Arithmetic.o : interface/Logic/Expr.hi
bin/Theories/Arithmetic.o : interface/Logic/Const.hi
bin/UnitB/AST.o : UnitB/AST.hs
bin/UnitB/AST.o : interface/Utilities/Graph.hi
bin/UnitB/AST.o : interface/Utilities/HeterogenousEquality.hi
bin/UnitB/AST.o : interface/Utilities/Format.hi
bin/UnitB/AST.o : interface/Theories/Arithmetic.hi
bin/UnitB/AST.o : interface/Theories/FunctionTheory.hi
bin/UnitB/AST.o : interface/Theories/SetTheory.hi
bin/UnitB/AST.o : interface/Logic/Theory.hi
bin/UnitB/AST.o : interface/Logic/Sequent.hi
bin/UnitB/AST.o : interface/Logic/Operator.hi
bin/UnitB/AST.o : interface/Logic/Label.hi
bin/UnitB/AST.o : interface/Logic/Classes.hi
bin/UnitB/AST.o : interface/Logic/ExpressionStore.hi
bin/UnitB/AST.o : interface/Logic/Const.hi
bin/UnitB/AST.o : interface/Logic/Expr.hi
bin/Code/Synthesis.o : Code/Synthesis.hs
bin/Code/Synthesis.o : interface/Utilities/Format.hi
bin/Code/Synthesis.o : interface/UnitB/AST.hi
bin/Code/Synthesis.o : interface/Theories/SetTheory.hi
bin/Code/Synthesis.o : interface/Logic/Classes.hi
bin/Code/Synthesis.o : interface/Logic/Expr.hi
bin/Code/Synthesis.o : interface/Logic/Const.hi
bin/SummaryGen.o : SummaryGen.hs
bin/SummaryGen.o : interface/UnitB/AST.hi
bin/SummaryGen.o : interface/Logic/ExpressionStore.hi
bin/SummaryGen.o : interface/Logic/Classes.hi
bin/Document/Expression.o : Document/Expression.hs
bin/Document/Expression.o : interface/Utilities/Graph.hi
bin/Document/Expression.o : interface/Utilities/Format.hi
bin/Document/Expression.o : interface/Utilities/Syntactic.hi
bin/Document/Expression.o : interface/Theories/FunctionTheory.hi
bin/Document/Expression.o : interface/Theories/SetTheory.hi
bin/Document/Expression.o : interface/UnitB/AST.hi
bin/Document/Expression.o : interface/Logic/Operator.hi
bin/Document/Expression.o : interface/Logic/Genericity.hi
bin/Document/Expression.o : interface/Logic/ExpressionStore.hi
bin/Document/Expression.o : interface/Logic/Expr.hi
bin/Document/Expression.o : interface/Logic/Const.hi
bin/Document/Expression.o : interface/Latex/Parser.hi
bin/Document/Expression.o : interface/Latex/Scanner.hi
bin/Theories/Notation.o : Theories/Notation.hs
bin/Theories/Notation.o : interface/Utilities/Graph.hi
bin/Theories/Notation.o : interface/Theories/SetTheory.hi
bin/Theories/Notation.o : interface/Theories/FunctionTheory.hi
bin/Theories/Notation.o : interface/Theories/Arithmetic.hi
bin/Theories/Notation.o : interface/Logic/OldOperator.hi
bin/Theories/Notation.o : interface/Logic/Operator.hi
bin/Document/Visitor.o : Document/Visitor.lhs
bin/Document/Visitor.o : interface/Utilities/Format.hi
bin/Document/Visitor.o : interface/Utilities/Syntactic.hi
bin/Document/Visitor.o : interface/Utilities/Error.hi
bin/Document/Visitor.o : interface/UnitB/AST.hi
bin/Document/Visitor.o : interface/Logic/Label.hi
bin/Document/Visitor.o : interface/Logic/ExpressionStore.hi
bin/Document/Visitor.o : interface/Latex/Parser.hi
bin/Document/Visitor.o : interface/Document/TypeList.hi
bin/Logic/Calculation.o : Logic/Calculation.hs
bin/Logic/Calculation.o : interface/Utilities/Syntactic.hi
bin/Logic/Calculation.o : interface/Utilities/Format.hi
bin/Logic/Calculation.o : interface/Logic/Theory.hi
bin/Logic/Calculation.o : interface/Logic/Sequent.hi
bin/Logic/Calculation.o : interface/Logic/Label.hi
bin/Logic/Calculation.o : interface/Logic/Operator.hi
bin/Logic/Calculation.o : interface/Logic/Genericity.hi
bin/Logic/Calculation.o : interface/Logic/Expr.hi
bin/Logic/Calculation.o : interface/Logic/Const.hi
bin/Logic/Calculation.o : interface/Logic/Classes.hi
bin/UnitB/PO.o : UnitB/PO.hs
bin/UnitB/PO.o : interface/Utilities/Syntactic.hi
bin/UnitB/PO.o : interface/Utilities/Format.hi
bin/UnitB/PO.o : interface/Z3/Z3.hi
bin/UnitB/PO.o : interface/UnitB/Feasibility.hi
bin/UnitB/PO.o : interface/UnitB/AST.hi
bin/UnitB/PO.o : interface/Logic/Theory.hi
bin/UnitB/PO.o : interface/Logic/Label.hi
bin/UnitB/PO.o : interface/Logic/Expr.hi
bin/UnitB/PO.o : interface/Logic/Const.hi
bin/UnitB/PO.o : interface/Logic/Classes.hi
bin/UnitB/PO.o : interface/Logic/Calculation.hi
bin/Logic/Tactics.o : Logic/Tactics.hs
bin/Logic/Tactics.o : interface/Utilities/Syntactic.hi
bin/Logic/Tactics.o : interface/Utilities/Format.hi
bin/Logic/Tactics.o : interface/Utilities/Error.hi
bin/Logic/Tactics.o : interface/Logic/Theory.hi
bin/Logic/Tactics.o : interface/Logic/Sequent.hi
bin/Logic/Tactics.o : interface/Logic/Label.hi
bin/Logic/Tactics.o : interface/Logic/Expr.hi
bin/Logic/Tactics.o : interface/Logic/Const.hi
bin/Logic/Tactics.o : interface/Logic/Classes.hi
bin/Logic/Tactics.o : interface/Logic/Calculation.hi
bin/Document/Proof.o : Document/Proof.hs
bin/Document/Proof.o : interface/Utilities/Syntactic.hi
bin/Document/Proof.o : interface/Utilities/Format.hi
bin/Document/Proof.o : interface/Utilities/Error.hi
bin/Document/Proof.o : interface/Logic/Theory.hi
bin/Document/Proof.o : interface/Logic/Tactics.hi
bin/Document/Proof.o : interface/Logic/Sequent.hi
bin/Document/Proof.o : interface/Logic/Operator.hi
bin/Document/Proof.o : interface/Logic/Label.hi
bin/Document/Proof.o : interface/Logic/Genericity.hi
bin/Document/Proof.o : interface/Logic/Const.hi
bin/Document/Proof.o : interface/Logic/Expr.hi
bin/Document/Proof.o : interface/Logic/Classes.hi
bin/Document/Proof.o : interface/Logic/Calculation.hi
bin/Document/Proof.o : interface/UnitB/PO.hi
bin/Document/Proof.o : interface/UnitB/AST.hi
bin/Document/Proof.o : interface/Latex/Parser.hi
bin/Document/Proof.o : interface/Document/Visitor.hi
bin/Document/Proof.o : interface/Document/Expression.hi
bin/Document/Refinement.o : Document/Refinement.hs
bin/Document/Refinement.o : interface/Utilities/Syntactic.hi
bin/Document/Refinement.o : interface/Utilities/Format.hi
bin/Document/Refinement.o : interface/Logic/Sequent.hi
bin/Document/Refinement.o : interface/Logic/Label.hi
bin/Document/Refinement.o : interface/Logic/Genericity.hi
bin/Document/Refinement.o : interface/Logic/Expr.hi
bin/Document/Refinement.o : interface/Logic/Const.hi
bin/Document/Refinement.o : interface/Latex/Parser.hi
bin/Document/Refinement.o : interface/UnitB/PO.hi
bin/Document/Refinement.o : interface/UnitB/AST.hi
bin/Document/Refinement.o : interface/Document/Proof.hi
bin/Document/Refinement.o : interface/Document/Visitor.hi
bin/Document/Context.o : Document/Context.hs
bin/Document/Context.o : interface/Utilities/Syntactic.hi
bin/Document/Context.o : interface/Utilities/Format.hi
bin/Document/Context.o : interface/Theories/Arithmetic.hi
bin/Document/Context.o : interface/Theories/FunctionTheory.hi
bin/Document/Context.o : interface/Theories/SetTheory.hi
bin/Document/Context.o : interface/UnitB/PO.hi
bin/Document/Context.o : interface/UnitB/AST.hi
bin/Document/Context.o : interface/Logic/Operator.hi
bin/Document/Context.o : interface/Logic/Label.hi
bin/Document/Context.o : interface/Logic/Expr.hi
bin/Document/Context.o : interface/Logic/Const.hi
bin/Document/Context.o : interface/Logic/Genericity.hi
bin/Document/Context.o : interface/Latex/Parser.hi
bin/Document/Context.o : interface/Document/Proof.hi
bin/Document/Context.o : interface/Document/Visitor.hi
bin/Document/Context.o : interface/Document/Expression.hi
bin/Document/Machine.o : Document/Machine.hs
bin/Document/Machine.o : interface/Utilities/Trace.hi
bin/Document/Machine.o : interface/Utilities/Syntactic.hi
bin/Document/Machine.o : interface/Utilities/Format.hi
bin/Document/Machine.o : interface/Z3/Z3.hi
bin/Document/Machine.o : interface/Theories/Arithmetic.hi
bin/Document/Machine.o : interface/Theories/FunctionTheory.hi
bin/Document/Machine.o : interface/Theories/SetTheory.hi
bin/Document/Machine.o : interface/UnitB/PO.hi
bin/Document/Machine.o : interface/UnitB/AST.hi
bin/Document/Machine.o : interface/SummaryGen.hi
bin/Document/Machine.o : interface/Logic/Tactics.hi
bin/Document/Machine.o : interface/Logic/Label.hi
bin/Document/Machine.o : interface/Logic/Sequent.hi
bin/Document/Machine.o : interface/Logic/ExpressionStore.hi
bin/Document/Machine.o : interface/Logic/Expr.hi
bin/Document/Machine.o : interface/Logic/Const.hi
bin/Document/Machine.o : interface/Latex/Parser.hi
bin/Document/Machine.o : interface/Document/Context.hi
bin/Document/Machine.o : interface/Document/Refinement.hi
bin/Document/Machine.o : interface/Document/Proof.hi
bin/Document/Machine.o : interface/Document/Visitor.hi
bin/Document/Machine.o : interface/Document/Expression.hi
bin/Interactive/Serialize.o : Interactive/Serialize.hs
bin/Interactive/Serialize.o : interface/UnitB/PO.hi
bin/Interactive/Serialize.o : interface/Logic/Sequent.hi
bin/Interactive/Serialize.o : interface/Logic/Label.hi
bin/Interactive/Serialize.o : interface/Logic/Expr.hi
bin/Document/Document.o : Document/Document.hs
bin/Document/Document.o : interface/Latex/Parser.hi
bin/Document/Document.o : interface/Document/Machine.hi
bin/Interactive/Config.o : Interactive/Config.hs
bin/Interactive/Pipeline.o : Interactive/Pipeline.hs
bin/Interactive/Pipeline.o : interface/Utilities/Trace.hi
bin/Interactive/Pipeline.o : interface/Utilities/Syntactic.hi
bin/Interactive/Pipeline.o : interface/Utilities/Format.hi
bin/Interactive/Pipeline.o : interface/Z3/Z3.hi
bin/Interactive/Pipeline.o : interface/UnitB/PO.hi
bin/Interactive/Pipeline.o : interface/UnitB/AST.hi
bin/Interactive/Pipeline.o : interface/Logic/Label.hi
bin/Interactive/Pipeline.o : interface/Interactive/Serialize.hi
bin/Interactive/Pipeline.o : interface/Interactive/Observable.hi
bin/Interactive/Pipeline.o : interface/Document/Document.hi
bin/Tests/UnitTest.o : Tests/UnitTest.hs
bin/Document/Tests/Cubes.o : Document/Tests/Cubes.hs
bin/Document/Tests/Cubes.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/Cubes.o : interface/UnitB/PO.hi
bin/Document/Tests/Cubes.o : interface/UnitB/AST.hi
bin/Document/Tests/Cubes.o : interface/Logic/Theory.hi
bin/Document/Tests/Cubes.o : interface/Logic/Calculation.hi
bin/Document/Tests/Cubes.o : interface/Logic/Label.hi
bin/Document/Tests/Cubes.o : interface/Logic/Expr.hi
bin/Document/Tests/Cubes.o : interface/Logic/Const.hi
bin/Document/Tests/Cubes.o : interface/Logic/Classes.hi
bin/Document/Tests/Cubes.o : interface/Tests/UnitTest.hi
bin/Document/Tests/Cubes.o : interface/Document/Document.hi
bin/Document/Tests/SmallMachine.o : Document/Tests/SmallMachine.hs
bin/Document/Tests/SmallMachine.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/SmallMachine.o : interface/Tests/UnitTest.hi
bin/Document/Tests/SmallMachine.o : interface/UnitB/PO.hi
bin/Document/Tests/SmallMachine.o : interface/UnitB/AST.hi
bin/Document/Tests/SmallMachine.o : interface/Logic/Label.hi
bin/Document/Tests/SmallMachine.o : interface/Logic/Expr.hi
bin/Document/Tests/SmallMachine.o : interface/Logic/Const.hi
bin/Document/Tests/SmallMachine.o : interface/Document/Document.hi
bin/Document/Tests/TrainStation.o : Document/Tests/TrainStation.hs
bin/Document/Tests/TrainStation.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/TrainStation.o : interface/Utilities/Format.hi
bin/Document/Tests/TrainStation.o : interface/Tests/UnitTest.hi
bin/Document/Tests/TrainStation.o : interface/Z3/Z3.hi
bin/Document/Tests/TrainStation.o : interface/Theories/Arithmetic.hi
bin/Document/Tests/TrainStation.o : interface/Theories/FunctionTheory.hi
bin/Document/Tests/TrainStation.o : interface/Theories/SetTheory.hi
bin/Document/Tests/TrainStation.o : interface/UnitB/PO.hi
bin/Document/Tests/TrainStation.o : interface/UnitB/AST.hi
bin/Document/Tests/TrainStation.o : interface/Logic/Theory.hi
bin/Document/Tests/TrainStation.o : interface/Logic/Label.hi
bin/Document/Tests/TrainStation.o : interface/Logic/Expr.hi
bin/Document/Tests/TrainStation.o : interface/Logic/Const.hi
bin/Document/Tests/TrainStation.o : interface/Logic/Calculation.hi
bin/Document/Tests/TrainStation.o : interface/Document/Document.hi
bin/Document/Tests/Lambdas.o : Document/Tests/Lambdas.hs
bin/Document/Tests/Lambdas.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/Lambdas.o : interface/Tests/UnitTest.hi
bin/Document/Tests/Lambdas.o : interface/UnitB/PO.hi
bin/Document/Tests/Lambdas.o : interface/UnitB/AST.hi
bin/Document/Tests/Lambdas.o : interface/Theories/FunctionTheory.hi
bin/Document/Tests/Lambdas.o : interface/Logic/Label.hi
bin/Document/Tests/Lambdas.o : interface/Logic/Expr.hi
bin/Document/Tests/Lambdas.o : interface/Logic/Const.hi
bin/Document/Tests/Lambdas.o : interface/Document/Document.hi
bin/Document/Tests/Phase.o : Document/Tests/Phase.hs
bin/Document/Tests/Phase.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/Phase.o : interface/Tests/UnitTest.hi
bin/Document/Tests/Phase.o : interface/Document/Document.hi
bin/Document/Tests/TrainStationRefinement.o : Document/Tests/TrainStationRefinement.hs
bin/Document/Tests/TrainStationRefinement.o : interface/Utilities/Syntactic.hi
bin/Document/Tests/TrainStationRefinement.o : interface/Utilities/Format.hi
bin/Document/Tests/TrainStationRefinement.o : interface/Tests/UnitTest.hi
bin/Document/Tests/TrainStationRefinement.o : interface/UnitB/PO.hi
bin/Document/Tests/TrainStationRefinement.o : interface/Document/Machine.hi
bin/Document/Tests/TrainStationSets.o : Document/Tests/TrainStationSets.hs
bin/Document/Tests/TrainStationSets.o : interface/Tests/UnitTest.hi
bin/Document/Tests/TrainStationSets.o : interface/UnitB/PO.hi
bin/Document/Tests/TrainStationSets.o : interface/Document/Document.hi
bin/Document/Tests/IndirectEq.o : Document/Tests/IndirectEq.hs
bin/Document/Tests/IndirectEq.o : interface/Tests/UnitTest.hi
bin/Document/Tests/IndirectEq.o : interface/UnitB/PO.hi
bin/Document/Tests/IndirectEq.o : interface/UnitB/AST.hi
bin/Document/Tests/IndirectEq.o : interface/Document/Document.hi
bin/Logic/TestGenericity.o : Logic/TestGenericity.hs
bin/Logic/TestGenericity.o : interface/Tests/UnitTest.hi
bin/Logic/TestGenericity.o : interface/Theories/SetTheory.hi
bin/Logic/TestGenericity.o : interface/Logic/Genericity.hi
bin/Logic/TestGenericity.o : interface/Logic/Expr.hi
bin/Logic/TestGenericity.o : interface/Logic/Const.hi
bin/Code/Test.o : Code/Test.hs
bin/Code/Test.o : interface/Tests/UnitTest.hi
bin/Code/Test.o : interface/UnitB/AST.hi
bin/Code/Test.o : interface/Logic/Const.hi
bin/Code/Test.o : interface/Logic/Label.hi
bin/Code/Test.o : interface/Document/Machine.hi
bin/Code/Test.o : interface/Code/Synthesis.hi
bin/Utilities/Test.o : Utilities/Test.hs
bin/Utilities/Test.o : interface/Utilities/Error.hi
bin/Utilities/Test.o : interface/Utilities/Syntactic.hi
bin/Utilities/Test.o : interface/Utilities/Format.hi
bin/Utilities/Test.o : interface/Tests/UnitTest.hi
bin/Utilities/Test.o : interface/Utilities/Graph.hi
bin/Utilities/Test.o : interface/Theories/FunctionTheory.hi
bin/Utilities/Test.o : interface/Theories/SetTheory.hi
bin/Utilities/Test.o : interface/Theories/Notation.hi
bin/Utilities/Test.o : interface/Theories/Arithmetic.hi
bin/Utilities/Test.o : interface/Logic/OldOperator.hi
bin/Utilities/Test.o : interface/Logic/Operator.hi
bin/Document/Test.o : Document/Test.hs
bin/Document/Test.o : interface/Utilities/Syntactic.hi
bin/Document/Test.o : interface/UnitB/PO.hi
bin/Document/Test.o : interface/Tests/UnitTest.hi
bin/Document/Test.o : interface/Latex/Scanner.hi
bin/Document/Test.o : interface/Latex/Parser.hi
bin/Document/Test.o : interface/Document/Tests/IndirectEq.hi
bin/Document/Test.o : interface/Document/Tests/TrainStationSets.hi
bin/Document/Test.o : interface/Document/Tests/TrainStationRefinement.hi
bin/Document/Test.o : interface/Document/Tests/Phase.hi
bin/Document/Test.o : interface/Document/Tests/Lambdas.hi
bin/Document/Test.o : interface/Document/Tests/TrainStation.hi
bin/Document/Test.o : interface/Document/Tests/SmallMachine.hi
bin/Document/Test.o : interface/Document/Tests/Cubes.hi
bin/Document/Test.o : interface/Document/Document.hi
bin/Z3/Test.o : Z3/Test.hs
bin/Z3/Test.o : interface/Tests/UnitTest.hi
bin/Z3/Test.o : interface/Utilities/Syntactic.hi
bin/Z3/Test.o : interface/UnitB/AST.hi
bin/Z3/Test.o : interface/UnitB/PO.hi
bin/Z3/Test.o : interface/Logic/Operator.hi
bin/Z3/Test.o : interface/Logic/Lambda.hi
bin/Z3/Test.o : interface/Logic/Expr.hi
bin/Z3/Test.o : interface/Logic/Const.hi
bin/Z3/Test.o : interface/Logic/Calculation.hi
bin/Z3/Test.o : interface/Z3/Z3.hi
bin/Latex/Test_Latex_Parser.o : Latex/Test_Latex_Parser.hs
bin/Latex/Test_Latex_Parser.o : interface/Utilities/Syntactic.hi
bin/Latex/Test_Latex_Parser.o : interface/Utilities/Format.hi
bin/Latex/Test_Latex_Parser.o : interface/Tests/UnitTest.hi
bin/Latex/Test_Latex_Parser.o : interface/Latex/Parser.hi
bin/UnitB/Test.o : UnitB/Test.hs
bin/UnitB/Test.o : interface/Utilities/Syntactic.hi
bin/UnitB/Test.o : interface/Tests/UnitTest.hi
bin/UnitB/Test.o : interface/Z3/Z3.hi
bin/UnitB/Test.o : interface/UnitB/PO.hi
bin/UnitB/Test.o : interface/UnitB/Feasibility.hi
bin/UnitB/Test.o : interface/UnitB/AST.hi
bin/UnitB/Test.o : interface/Theories/FunctionTheory.hi
bin/UnitB/Test.o : interface/Logic/TestGenericity.hi
bin/UnitB/Test.o : interface/Logic/Label.hi
bin/UnitB/Test.o : interface/Logic/Expr.hi
bin/UnitB/Test.o : interface/Logic/Const.hi
bin/UnitB/Test.o : interface/Logic/Classes.hi
bin/Tools/Heap.o : Tools/Heap.hs
bin/Tools/BuildSystem.o : Tools/BuildSystem.hs
bin/Main.o : run_tests.hs
bin/Main.o : interface/Interactive/Config.hi
bin/Main.o : verify.hs
bin/Main.o : interface/Utilities/Syntactic.hi
bin/Main.o : interface/UnitB/PO.hi
bin/Main.o : interface/UnitB/AST.hi
bin/Main.o : interface/Document/Document.hi
bin/Main.o : continuous.hs
bin/Main.o : interface/Utilities/Trace.hi
bin/Main.o : interface/Utilities/Syntactic.hi
bin/Main.o : interface/Z3/Z3.hi
bin/Main.o : interface/UnitB/PO.hi
bin/Main.o : interface/UnitB/AST.hi
bin/Main.o : interface/Logic/Label.hi
bin/Main.o : interface/Document/Document.hi
bin/Main.o : interface/Interactive/Config.hi
bin/Main.o : interface/Interactive/Pipeline.hi
bin/Main.o : test.hs
bin/Main.o : interface/Tests/UnitTest.hi
bin/Main.o : interface/Code/Test.hi
bin/Main.o : interface/Utilities/Test.hi
bin/Main.o : interface/Document/Test.hi
bin/Main.o : interface/Z3/Test.hi
bin/Main.o : interface/Latex/Test_Latex_Parser.hi
bin/Main.o : interface/UnitB/Test.hi
bin/Main.o : compile.hs
bin/Main.o : interface/Tools/BuildSystem.hi
bin/Main.o : periodic.hs
bin/Main.o : interface/Tools/Heap.hi
bin/Main.o : interface/Tools/BuildSystem.hi
# DO NOT DELETE: End of Haskell dependencies
bin/Utilities/Graph.o : Utilities/Graph.hs
bin/Utilities/HeterogenousEquality.o : Utilities/HeterogenousEquality.hs
bin/Utilities/Format.o : Utilities/Format.hs
bin/Logic/Classes.o : Logic/Classes.hs
bin/Logic/Expr.o : Logic/Expr.hs
bin/Logic/Expr.o : bin/Utilities/Format.o
bin/Logic/Expr.o : bin/Logic/Classes.o
bin/Logic/Genericity.o : Logic/Genericity.hs
bin/Logic/Genericity.o : bin/Utilities/Format.o
bin/Logic/Genericity.o : bin/Logic/Classes.o
bin/Logic/Genericity.o : bin/Logic/Expr.o
bin/Utilities/Trace.o : Utilities/Trace.hs
bin/Utilities/Trace.o : bin/Utilities/Format.o
bin/Interactive/Observable.o : Interactive/Observable.hs
bin/Interactive/Observable.o : bin/Utilities/Trace.o
bin/Utilities/Syntactic.o : Utilities/Syntactic.hs
bin/Utilities/Syntactic.o : bin/Utilities/Format.o
bin/Logic/Const.o : Logic/Const.hs
bin/Logic/Const.o : bin/Utilities/Syntactic.o
bin/Logic/Const.o : bin/Utilities/Format.o
bin/Logic/Const.o : bin/Logic/Genericity.o
bin/Logic/Const.o : bin/Logic/Expr.o
bin/Logic/ExpressionStore.o : Logic/ExpressionStore.hs
bin/Logic/ExpressionStore.o : bin/Logic/Const.o
bin/Logic/ExpressionStore.o : bin/Logic/Classes.o
bin/Logic/ExpressionStore.o : bin/Logic/Expr.o
bin/Logic/Operator.o : Logic/Operator.hs
bin/Logic/Operator.o : bin/Utilities/Graph.o
bin/Logic/Operator.o : bin/Utilities/Graph.o
bin/Logic/Operator.o : bin/Utilities/Format.o
bin/Logic/Operator.o : bin/Logic/Const.o
bin/Logic/Operator.o : bin/Logic/Expr.o
bin/Logic/OldOperator.o : Logic/OldOperator.hs
bin/Logic/OldOperator.o : bin/Logic/Operator.o
bin/Logic/Sequent.o : Logic/Sequent.hs
bin/Logic/Sequent.o : bin/Utilities/Format.o
bin/Logic/Sequent.o : bin/Logic/Const.o
bin/Logic/Sequent.o : bin/Logic/Expr.o
bin/Logic/Lambda.o : Logic/Lambda.hs
bin/Logic/Lambda.o : bin/Logic/Sequent.o
bin/Logic/Lambda.o : bin/Logic/Genericity.o
bin/Logic/Lambda.o : bin/Logic/Expr.o
bin/Logic/Lambda.o : bin/Logic/Const.o
bin/Logic/Lambda.o : bin/Logic/Classes.o
bin/UnitB/Feasibility.o : UnitB/Feasibility.lhs
bin/UnitB/Feasibility.o : bin/Logic/Const.o
bin/UnitB/Feasibility.o : bin/Logic/Expr.o
bin/Utilities/Error.o : Utilities/Error.hs
bin/Utilities/Error.o : bin/Utilities/Syntactic.o
bin/Latex/Scanner.o : Latex/Scanner.hs
bin/Latex/Scanner.o : bin/Utilities/Syntactic.o
bin/Latex/Parser.o : Latex/Parser.hs
bin/Latex/Parser.o : bin/Utilities/Syntactic.o
bin/Latex/Parser.o : bin/Utilities/Graph.o
bin/Latex/Parser.o : bin/Utilities/Format.o
bin/Latex/Parser.o : bin/Latex/Scanner.o
bin/Document/TypeList.o : Document/TypeList.hs
bin/Document/TypeList.o : bin/Utilities/Syntactic.o
bin/Document/TypeList.o : bin/Latex/Parser.o
bin/Logic/Label.o : Logic/Label.hs
bin/Logic/Label.o : bin/Logic/Classes.o
bin/Z3/Z3.o : Z3/Z3.hs
bin/Z3/Z3.o : bin/Logic/Sequent.o
bin/Z3/Z3.o : bin/Logic/Lambda.o
bin/Z3/Z3.o : bin/Logic/Label.o
bin/Z3/Z3.o : bin/Logic/Const.o
bin/Z3/Z3.o : bin/Logic/Classes.o
bin/Z3/Z3.o : bin/Logic/Expr.o
bin/Logic/Theory.o : Logic/Theory.hs
bin/Logic/Theory.o : bin/Utilities/HeterogenousEquality.o
bin/Logic/Theory.o : bin/Utilities/Syntactic.o
bin/Logic/Theory.o : bin/Logic/Sequent.o
bin/Logic/Theory.o : bin/Logic/Operator.o
bin/Logic/Theory.o : bin/Logic/Label.o
bin/Logic/Theory.o : bin/Logic/Expr.o
bin/Theories/SetTheory.o : Theories/SetTheory.hs
bin/Theories/SetTheory.o : bin/Utilities/Format.o
bin/Theories/SetTheory.o : bin/Logic/Theory.o
bin/Theories/SetTheory.o : bin/Logic/Operator.o
bin/Theories/SetTheory.o : bin/Logic/Label.o
bin/Theories/SetTheory.o : bin/Logic/Genericity.o
bin/Theories/SetTheory.o : bin/Logic/Expr.o
bin/Theories/SetTheory.o : bin/Logic/Const.o
bin/Theories/FunctionTheory.o : Theories/FunctionTheory.hs
bin/Theories/FunctionTheory.o : bin/Theories/SetTheory.o
bin/Theories/FunctionTheory.o : bin/Logic/Theory.o
bin/Theories/FunctionTheory.o : bin/Logic/Operator.o
bin/Theories/FunctionTheory.o : bin/Logic/Label.o
bin/Theories/FunctionTheory.o : bin/Logic/Genericity.o
bin/Theories/FunctionTheory.o : bin/Logic/Expr.o
bin/Theories/FunctionTheory.o : bin/Logic/Const.o
bin/Theories/Arithmetic.o : Theories/Arithmetic.hs
bin/Theories/Arithmetic.o : bin/Theories/FunctionTheory.o
bin/Theories/Arithmetic.o : bin/Logic/Theory.o
bin/Theories/Arithmetic.o : bin/Logic/Operator.o
bin/Theories/Arithmetic.o : bin/Logic/Label.o
bin/Theories/Arithmetic.o : bin/Logic/Expr.o
bin/Theories/Arithmetic.o : bin/Logic/Const.o
bin/UnitB/AST.o : UnitB/AST.hs
bin/UnitB/AST.o : bin/Utilities/Graph.o
bin/UnitB/AST.o : bin/Utilities/HeterogenousEquality.o
bin/UnitB/AST.o : bin/Utilities/Format.o
bin/UnitB/AST.o : bin/Theories/Arithmetic.o
bin/UnitB/AST.o : bin/Theories/FunctionTheory.o
bin/UnitB/AST.o : bin/Theories/SetTheory.o
bin/UnitB/AST.o : bin/Logic/Theory.o
bin/UnitB/AST.o : bin/Logic/Sequent.o
bin/UnitB/AST.o : bin/Logic/Operator.o
bin/UnitB/AST.o : bin/Logic/Label.o
bin/UnitB/AST.o : bin/Logic/Classes.o
bin/UnitB/AST.o : bin/Logic/ExpressionStore.o
bin/UnitB/AST.o : bin/Logic/Const.o
bin/UnitB/AST.o : bin/Logic/Expr.o
bin/Code/Synthesis.o : Code/Synthesis.hs
bin/Code/Synthesis.o : bin/Utilities/Format.o
bin/Code/Synthesis.o : bin/UnitB/AST.o
bin/Code/Synthesis.o : bin/Theories/SetTheory.o
bin/Code/Synthesis.o : bin/Logic/Classes.o
bin/Code/Synthesis.o : bin/Logic/Expr.o
bin/Code/Synthesis.o : bin/Logic/Const.o
bin/SummaryGen.o : SummaryGen.hs
bin/SummaryGen.o : bin/UnitB/AST.o
bin/SummaryGen.o : bin/Logic/ExpressionStore.o
bin/SummaryGen.o : bin/Logic/Classes.o
bin/Document/Expression.o : Document/Expression.hs
bin/Document/Expression.o : bin/Utilities/Graph.o
bin/Document/Expression.o : bin/Utilities/Format.o
bin/Document/Expression.o : bin/Utilities/Syntactic.o
bin/Document/Expression.o : bin/Theories/FunctionTheory.o
bin/Document/Expression.o : bin/Theories/SetTheory.o
bin/Document/Expression.o : bin/UnitB/AST.o
bin/Document/Expression.o : bin/Logic/Operator.o
bin/Document/Expression.o : bin/Logic/Genericity.o
bin/Document/Expression.o : bin/Logic/ExpressionStore.o
bin/Document/Expression.o : bin/Logic/Expr.o
bin/Document/Expression.o : bin/Logic/Const.o
bin/Document/Expression.o : bin/Latex/Parser.o
bin/Document/Expression.o : bin/Latex/Scanner.o
bin/Theories/Notation.o : Theories/Notation.hs
bin/Theories/Notation.o : bin/Utilities/Graph.o
bin/Theories/Notation.o : bin/Theories/SetTheory.o
bin/Theories/Notation.o : bin/Theories/FunctionTheory.o
bin/Theories/Notation.o : bin/Theories/Arithmetic.o
bin/Theories/Notation.o : bin/Logic/OldOperator.o
bin/Theories/Notation.o : bin/Logic/Operator.o
bin/Document/Visitor.o : Document/Visitor.lhs
bin/Document/Visitor.o : bin/Utilities/Format.o
bin/Document/Visitor.o : bin/Utilities/Syntactic.o
bin/Document/Visitor.o : bin/Utilities/Error.o
bin/Document/Visitor.o : bin/UnitB/AST.o
bin/Document/Visitor.o : bin/Logic/Label.o
bin/Document/Visitor.o : bin/Logic/ExpressionStore.o
bin/Document/Visitor.o : bin/Latex/Parser.o
bin/Document/Visitor.o : bin/Document/TypeList.o
bin/Logic/Calculation.o : Logic/Calculation.hs
bin/Logic/Calculation.o : bin/Utilities/Syntactic.o
bin/Logic/Calculation.o : bin/Utilities/Format.o
bin/Logic/Calculation.o : bin/Logic/Theory.o
bin/Logic/Calculation.o : bin/Logic/Sequent.o
bin/Logic/Calculation.o : bin/Logic/Label.o
bin/Logic/Calculation.o : bin/Logic/Operator.o
bin/Logic/Calculation.o : bin/Logic/Genericity.o
bin/Logic/Calculation.o : bin/Logic/Expr.o
bin/Logic/Calculation.o : bin/Logic/Const.o
bin/Logic/Calculation.o : bin/Logic/Classes.o
bin/UnitB/PO.o : UnitB/PO.hs
bin/UnitB/PO.o : bin/Utilities/Syntactic.o
bin/UnitB/PO.o : bin/Utilities/Format.o
bin/UnitB/PO.o : bin/Z3/Z3.o
bin/UnitB/PO.o : bin/UnitB/Feasibility.o
bin/UnitB/PO.o : bin/UnitB/AST.o
bin/UnitB/PO.o : bin/Logic/Theory.o
bin/UnitB/PO.o : bin/Logic/Label.o
bin/UnitB/PO.o : bin/Logic/Expr.o
bin/UnitB/PO.o : bin/Logic/Const.o
bin/UnitB/PO.o : bin/Logic/Classes.o
bin/UnitB/PO.o : bin/Logic/Calculation.o
bin/Logic/Tactics.o : Logic/Tactics.hs
bin/Logic/Tactics.o : bin/Utilities/Syntactic.o
bin/Logic/Tactics.o : bin/Utilities/Format.o
bin/Logic/Tactics.o : bin/Utilities/Error.o
bin/Logic/Tactics.o : bin/Logic/Theory.o
bin/Logic/Tactics.o : bin/Logic/Sequent.o
bin/Logic/Tactics.o : bin/Logic/Label.o
bin/Logic/Tactics.o : bin/Logic/Expr.o
bin/Logic/Tactics.o : bin/Logic/Const.o
bin/Logic/Tactics.o : bin/Logic/Classes.o
bin/Logic/Tactics.o : bin/Logic/Calculation.o
bin/Document/Proof.o : Document/Proof.hs
bin/Document/Proof.o : bin/Utilities/Syntactic.o
bin/Document/Proof.o : bin/Utilities/Format.o
bin/Document/Proof.o : bin/Utilities/Error.o
bin/Document/Proof.o : bin/Logic/Theory.o
bin/Document/Proof.o : bin/Logic/Tactics.o
bin/Document/Proof.o : bin/Logic/Sequent.o
bin/Document/Proof.o : bin/Logic/Operator.o
bin/Document/Proof.o : bin/Logic/Label.o
bin/Document/Proof.o : bin/Logic/Genericity.o
bin/Document/Proof.o : bin/Logic/Const.o
bin/Document/Proof.o : bin/Logic/Expr.o
bin/Document/Proof.o : bin/Logic/Classes.o
bin/Document/Proof.o : bin/Logic/Calculation.o
bin/Document/Proof.o : bin/UnitB/PO.o
bin/Document/Proof.o : bin/UnitB/AST.o
bin/Document/Proof.o : bin/Latex/Parser.o
bin/Document/Proof.o : bin/Document/Visitor.o
bin/Document/Proof.o : bin/Document/Expression.o
bin/Document/Refinement.o : Document/Refinement.hs
bin/Document/Refinement.o : bin/Utilities/Syntactic.o
bin/Document/Refinement.o : bin/Utilities/Format.o
bin/Document/Refinement.o : bin/Logic/Sequent.o
bin/Document/Refinement.o : bin/Logic/Label.o
bin/Document/Refinement.o : bin/Logic/Genericity.o
bin/Document/Refinement.o : bin/Logic/Expr.o
bin/Document/Refinement.o : bin/Logic/Const.o
bin/Document/Refinement.o : bin/Latex/Parser.o
bin/Document/Refinement.o : bin/UnitB/PO.o
bin/Document/Refinement.o : bin/UnitB/AST.o
bin/Document/Refinement.o : bin/Document/Proof.o
bin/Document/Refinement.o : bin/Document/Visitor.o
bin/Document/Context.o : Document/Context.hs
bin/Document/Context.o : bin/Utilities/Syntactic.o
bin/Document/Context.o : bin/Utilities/Format.o
bin/Document/Context.o : bin/Theories/Arithmetic.o
bin/Document/Context.o : bin/Theories/FunctionTheory.o
bin/Document/Context.o : bin/Theories/SetTheory.o
bin/Document/Context.o : bin/UnitB/PO.o
bin/Document/Context.o : bin/UnitB/AST.o
bin/Document/Context.o : bin/Logic/Operator.o
bin/Document/Context.o : bin/Logic/Label.o
bin/Document/Context.o : bin/Logic/Expr.o
bin/Document/Context.o : bin/Logic/Const.o
bin/Document/Context.o : bin/Logic/Genericity.o
bin/Document/Context.o : bin/Latex/Parser.o
bin/Document/Context.o : bin/Document/Proof.o
bin/Document/Context.o : bin/Document/Visitor.o
bin/Document/Context.o : bin/Document/Expression.o
bin/Document/Machine.o : Document/Machine.hs
bin/Document/Machine.o : bin/Utilities/Trace.o
bin/Document/Machine.o : bin/Utilities/Syntactic.o
bin/Document/Machine.o : bin/Utilities/Format.o
bin/Document/Machine.o : bin/Z3/Z3.o
bin/Document/Machine.o : bin/Theories/Arithmetic.o
bin/Document/Machine.o : bin/Theories/FunctionTheory.o
bin/Document/Machine.o : bin/Theories/SetTheory.o
bin/Document/Machine.o : bin/UnitB/PO.o
bin/Document/Machine.o : bin/UnitB/AST.o
bin/Document/Machine.o : bin/SummaryGen.o
bin/Document/Machine.o : bin/Logic/Tactics.o
bin/Document/Machine.o : bin/Logic/Label.o
bin/Document/Machine.o : bin/Logic/Sequent.o
bin/Document/Machine.o : bin/Logic/ExpressionStore.o
bin/Document/Machine.o : bin/Logic/Expr.o
bin/Document/Machine.o : bin/Logic/Const.o
bin/Document/Machine.o : bin/Latex/Parser.o
bin/Document/Machine.o : bin/Document/Context.o
bin/Document/Machine.o : bin/Document/Refinement.o
bin/Document/Machine.o : bin/Document/Proof.o
bin/Document/Machine.o : bin/Document/Visitor.o
bin/Document/Machine.o : bin/Document/Expression.o
bin/Interactive/Serialize.o : Interactive/Serialize.hs
bin/Interactive/Serialize.o : bin/UnitB/PO.o
bin/Interactive/Serialize.o : bin/Logic/Sequent.o
bin/Interactive/Serialize.o : bin/Logic/Label.o
bin/Interactive/Serialize.o : bin/Logic/Expr.o
bin/Document/Document.o : Document/Document.hs
bin/Document/Document.o : bin/Latex/Parser.o
bin/Document/Document.o : bin/Document/Machine.o
bin/Interactive/Config.o : Interactive/Config.hs
bin/Interactive/Pipeline.o : Interactive/Pipeline.hs
bin/Interactive/Pipeline.o : bin/Utilities/Trace.o
bin/Interactive/Pipeline.o : bin/Utilities/Syntactic.o
bin/Interactive/Pipeline.o : bin/Utilities/Format.o
bin/Interactive/Pipeline.o : bin/Z3/Z3.o
bin/Interactive/Pipeline.o : bin/UnitB/PO.o
bin/Interactive/Pipeline.o : bin/UnitB/AST.o
bin/Interactive/Pipeline.o : bin/Logic/Label.o
bin/Interactive/Pipeline.o : bin/Interactive/Serialize.o
bin/Interactive/Pipeline.o : bin/Interactive/Observable.o
bin/Interactive/Pipeline.o : bin/Document/Document.o
bin/Tests/UnitTest.o : Tests/UnitTest.hs
bin/Document/Tests/Cubes.o : Document/Tests/Cubes.hs
bin/Document/Tests/Cubes.o : bin/Utilities/Syntactic.o
bin/Document/Tests/Cubes.o : bin/UnitB/PO.o
bin/Document/Tests/Cubes.o : bin/UnitB/AST.o
bin/Document/Tests/Cubes.o : bin/Logic/Theory.o
bin/Document/Tests/Cubes.o : bin/Logic/Calculation.o
bin/Document/Tests/Cubes.o : bin/Logic/Label.o
bin/Document/Tests/Cubes.o : bin/Logic/Expr.o
bin/Document/Tests/Cubes.o : bin/Logic/Const.o
bin/Document/Tests/Cubes.o : bin/Logic/Classes.o
bin/Document/Tests/Cubes.o : bin/Tests/UnitTest.o
bin/Document/Tests/Cubes.o : bin/Document/Document.o
bin/Document/Tests/SmallMachine.o : Document/Tests/SmallMachine.hs
bin/Document/Tests/SmallMachine.o : bin/Utilities/Syntactic.o
bin/Document/Tests/SmallMachine.o : bin/Tests/UnitTest.o
bin/Document/Tests/SmallMachine.o : bin/UnitB/PO.o
bin/Document/Tests/SmallMachine.o : bin/UnitB/AST.o
bin/Document/Tests/SmallMachine.o : bin/Logic/Label.o
bin/Document/Tests/SmallMachine.o : bin/Logic/Expr.o
bin/Document/Tests/SmallMachine.o : bin/Logic/Const.o
bin/Document/Tests/SmallMachine.o : bin/Document/Document.o
bin/Document/Tests/TrainStation.o : Document/Tests/TrainStation.hs
bin/Document/Tests/TrainStation.o : bin/Utilities/Syntactic.o
bin/Document/Tests/TrainStation.o : bin/Utilities/Format.o
bin/Document/Tests/TrainStation.o : bin/Tests/UnitTest.o
bin/Document/Tests/TrainStation.o : bin/Z3/Z3.o
bin/Document/Tests/TrainStation.o : bin/Theories/Arithmetic.o
bin/Document/Tests/TrainStation.o : bin/Theories/FunctionTheory.o
bin/Document/Tests/TrainStation.o : bin/Theories/SetTheory.o
bin/Document/Tests/TrainStation.o : bin/UnitB/PO.o
bin/Document/Tests/TrainStation.o : bin/UnitB/AST.o
bin/Document/Tests/TrainStation.o : bin/Logic/Theory.o
bin/Document/Tests/TrainStation.o : bin/Logic/Label.o
bin/Document/Tests/TrainStation.o : bin/Logic/Expr.o
bin/Document/Tests/TrainStation.o : bin/Logic/Const.o
bin/Document/Tests/TrainStation.o : bin/Logic/Calculation.o
bin/Document/Tests/TrainStation.o : bin/Document/Document.o
bin/Document/Tests/Lambdas.o : Document/Tests/Lambdas.hs
bin/Document/Tests/Lambdas.o : bin/Utilities/Syntactic.o
bin/Document/Tests/Lambdas.o : bin/Tests/UnitTest.o
bin/Document/Tests/Lambdas.o : bin/UnitB/PO.o
bin/Document/Tests/Lambdas.o : bin/UnitB/AST.o
bin/Document/Tests/Lambdas.o : bin/Theories/FunctionTheory.o
bin/Document/Tests/Lambdas.o : bin/Logic/Label.o
bin/Document/Tests/Lambdas.o : bin/Logic/Expr.o
bin/Document/Tests/Lambdas.o : bin/Logic/Const.o
bin/Document/Tests/Lambdas.o : bin/Document/Document.o
bin/Document/Tests/Phase.o : Document/Tests/Phase.hs
bin/Document/Tests/Phase.o : bin/Utilities/Syntactic.o
bin/Document/Tests/Phase.o : bin/Tests/UnitTest.o
bin/Document/Tests/Phase.o : bin/Document/Document.o
bin/Document/Tests/TrainStationRefinement.o : Document/Tests/TrainStationRefinement.hs
bin/Document/Tests/TrainStationRefinement.o : bin/Utilities/Syntactic.o
bin/Document/Tests/TrainStationRefinement.o : bin/Utilities/Format.o
bin/Document/Tests/TrainStationRefinement.o : bin/Tests/UnitTest.o
bin/Document/Tests/TrainStationRefinement.o : bin/UnitB/PO.o
bin/Document/Tests/TrainStationRefinement.o : bin/Document/Machine.o
bin/Document/Tests/TrainStationSets.o : Document/Tests/TrainStationSets.hs
bin/Document/Tests/TrainStationSets.o : bin/Tests/UnitTest.o
bin/Document/Tests/TrainStationSets.o : bin/UnitB/PO.o
bin/Document/Tests/TrainStationSets.o : bin/Document/Document.o
bin/Document/Tests/IndirectEq.o : Document/Tests/IndirectEq.hs
bin/Document/Tests/IndirectEq.o : bin/Tests/UnitTest.o
bin/Document/Tests/IndirectEq.o : bin/UnitB/PO.o
bin/Document/Tests/IndirectEq.o : bin/UnitB/AST.o
bin/Document/Tests/IndirectEq.o : bin/Document/Document.o
bin/Logic/TestGenericity.o : Logic/TestGenericity.hs
bin/Logic/TestGenericity.o : bin/Tests/UnitTest.o
bin/Logic/TestGenericity.o : bin/Theories/SetTheory.o
bin/Logic/TestGenericity.o : bin/Logic/Genericity.o
bin/Logic/TestGenericity.o : bin/Logic/Expr.o
bin/Logic/TestGenericity.o : bin/Logic/Const.o
bin/Code/Test.o : Code/Test.hs
bin/Code/Test.o : bin/Tests/UnitTest.o
bin/Code/Test.o : bin/UnitB/AST.o
bin/Code/Test.o : bin/Logic/Const.o
bin/Code/Test.o : bin/Logic/Label.o
bin/Code/Test.o : bin/Document/Machine.o
bin/Code/Test.o : bin/Code/Synthesis.o
bin/Utilities/Test.o : Utilities/Test.hs
bin/Utilities/Test.o : bin/Utilities/Error.o
bin/Utilities/Test.o : bin/Utilities/Syntactic.o
bin/Utilities/Test.o : bin/Utilities/Format.o
bin/Utilities/Test.o : bin/Tests/UnitTest.o
bin/Utilities/Test.o : bin/Utilities/Graph.o
bin/Utilities/Test.o : bin/Theories/FunctionTheory.o
bin/Utilities/Test.o : bin/Theories/SetTheory.o
bin/Utilities/Test.o : bin/Theories/Notation.o
bin/Utilities/Test.o : bin/Theories/Arithmetic.o
bin/Utilities/Test.o : bin/Logic/OldOperator.o
bin/Utilities/Test.o : bin/Logic/Operator.o
bin/Document/Test.o : Document/Test.hs
bin/Document/Test.o : bin/Utilities/Syntactic.o
bin/Document/Test.o : bin/UnitB/PO.o
bin/Document/Test.o : bin/Tests/UnitTest.o
bin/Document/Test.o : bin/Latex/Scanner.o
bin/Document/Test.o : bin/Latex/Parser.o
bin/Document/Test.o : bin/Document/Tests/IndirectEq.o
bin/Document/Test.o : bin/Document/Tests/TrainStationSets.o
bin/Document/Test.o : bin/Document/Tests/TrainStationRefinement.o
bin/Document/Test.o : bin/Document/Tests/Phase.o
bin/Document/Test.o : bin/Document/Tests/Lambdas.o
bin/Document/Test.o : bin/Document/Tests/TrainStation.o
bin/Document/Test.o : bin/Document/Tests/SmallMachine.o
bin/Document/Test.o : bin/Document/Tests/Cubes.o
bin/Document/Test.o : bin/Document/Document.o
bin/Z3/Test.o : Z3/Test.hs
bin/Z3/Test.o : bin/Tests/UnitTest.o
bin/Z3/Test.o : bin/Utilities/Syntactic.o
bin/Z3/Test.o : bin/UnitB/AST.o
bin/Z3/Test.o : bin/UnitB/PO.o
bin/Z3/Test.o : bin/Logic/Operator.o
bin/Z3/Test.o : bin/Logic/Lambda.o
bin/Z3/Test.o : bin/Logic/Expr.o
bin/Z3/Test.o : bin/Logic/Const.o
bin/Z3/Test.o : bin/Logic/Calculation.o
bin/Z3/Test.o : bin/Z3/Z3.o
bin/Latex/Test_Latex_Parser.o : Latex/Test_Latex_Parser.hs
bin/Latex/Test_Latex_Parser.o : bin/Utilities/Syntactic.o
bin/Latex/Test_Latex_Parser.o : bin/Utilities/Format.o
bin/Latex/Test_Latex_Parser.o : bin/Tests/UnitTest.o
bin/Latex/Test_Latex_Parser.o : bin/Latex/Parser.o
bin/UnitB/Test.o : UnitB/Test.hs
bin/UnitB/Test.o : bin/Utilities/Syntactic.o
bin/UnitB/Test.o : bin/Tests/UnitTest.o
bin/UnitB/Test.o : bin/Z3/Z3.o
bin/UnitB/Test.o : bin/UnitB/PO.o
bin/UnitB/Test.o : bin/UnitB/Feasibility.o
bin/UnitB/Test.o : bin/UnitB/AST.o
bin/UnitB/Test.o : bin/Theories/FunctionTheory.o
bin/UnitB/Test.o : bin/Logic/TestGenericity.o
bin/UnitB/Test.o : bin/Logic/Label.o
bin/UnitB/Test.o : bin/Logic/Expr.o
bin/UnitB/Test.o : bin/Logic/Const.o
bin/UnitB/Test.o : bin/Logic/Classes.o
bin/Tools/Heap.o : Tools/Heap.hs
bin/Tools/BuildSystem.o : Tools/BuildSystem.hs
bin/Main.o : run_tests.hs
bin/Main.o : interface/Interactive/Config.hi
bin/Main.o : verify.hs
bin/Main.o : interface/Utilities/Syntactic.hi
bin/Main.o : interface/UnitB/PO.hi
bin/Main.o : interface/UnitB/AST.hi
bin/Main.o : interface/Document/Document.hi
bin/Main.o : continuous.hs
bin/Main.o : interface/Utilities/Trace.hi
bin/Main.o : interface/Utilities/Syntactic.hi
bin/Main.o : interface/Z3/Z3.hi
bin/Main.o : interface/UnitB/PO.hi
bin/Main.o : interface/UnitB/AST.hi
bin/Main.o : interface/Logic/Label.hi
bin/Main.o : interface/Document/Document.hi
bin/Main.o : interface/Interactive/Config.hi
bin/Main.o : interface/Interactive/Pipeline.hi
bin/Main.o : test.hs
bin/Main.o : interface/Tests/UnitTest.hi
bin/Main.o : interface/Code/Test.hi
bin/Main.o : interface/Utilities/Test.hi
bin/Main.o : interface/Document/Test.hi
bin/Main.o : interface/Z3/Test.hi
bin/Main.o : interface/Latex/Test_Latex_Parser.hi
bin/Main.o : interface/UnitB/Test.hi
bin/Main.o : compile.hs
bin/Main.o : interface/Tools/BuildSystem.hi
bin/Main.o : periodic.hs
bin/Main.o : interface/Tools/Heap.hi
bin/Main.o : interface/Tools/BuildSystem.hi
